### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ege-erdogan** [ZeligSim/Zelig#14]
## Analytics
- [ ] move from percent mining power  to hash rate per node (for PoW)
    - [ ] can then analyze nodes' computational work better
- [x] no. of  transactions waiting in mempool at each step
- [ ] amount of currency generated (with mining in PoW), meaningful with changing difficulty (dynamic network)

**Comment by ege-erdogan** [comment]
## Network

- [ ] dynamic  network (new nodes joining and leaving)
- [ ] node leave/join protocol (updating blockchain / removing dead  connections)
- [ ] (?) network statistics

**Comment by ege-erdogan** [comment]
## Consensus/Data

- [ ] Nodes update tx  pool based on orphan blocks 
- [ ] (?) Computationally limited nodes (number of operations (send block, mine, etc.) in one step limited)
- [ ] (?) Nodes' currency balance
- [ ] Distribution for number of tx generated  by node (can also be made configurable)

**Comment by ege-erdogan** [comment]
##  Experiments

- [ ] Performance  comparison with other simulators (running time etc.)
- [ ] Compare with small-scale network running bitcoind ([1] section IV)
- [ ] Simulate attacks

[1]: https://ieeexplore.ieee.org/abstract/document/9500200
